name: Pipeline para Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Troque pela versão que você usa

      - name: Instalar Dependências
        run: npm install

      - name: Rodar Testes
        run: npm test

      - name: Construir Aplicação
        run: npm run build
d